# Generated by Django 3.2.18 on 2023-03-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20230317_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
